### ISSUE TITLE
Tradall IT VAT Enhancement

### ISSUE THREAD

**Issue by koushik-ac** [beezlabs-org/l3-support#2]
Hi Team,

We have a new enhancement request in the automation Tradall IT VAT Warehouse. The current process is being performed for Company Code 3290. We need extend this process for a list of companies. Currently, the single company code is stored as constant in the first bot. The files which get downloaded from SAP must have company code attached to the file name. This company code should be passed as Input Proposal to the bot and this value is received in the bot logic and attached to the file name.

The final file which gets uploaded to the Share Point also has the company code in the file name. This logic should also be changed to get the company code value from Input Proposal and change the file name accordingly.
 
We need to check how the current logic behaves if there is no data in SAP for given inputs. If the automation fails in that scenario, we need to make changes to the logic to handle such scenarios.

**Comment by Sakthi1502** [comment]
Hi @karthikeyan23 @mbm-hub Below are the actions to be done for Tradall IT VAT Enhancement after discussion with @koushik-ac. Development and Testing should take 2-3 Days.
1) Workflow Design Change.
2) Bot to handle 38 Company code instead of single company code and upload report templates to Sharepoint.
3) SAP Report Status validation check to be included at the code level. If report is not available Bot should check for next GL Account or next company code.
4) File Name change to be handled at the code level and exposed in Execution State.
5) Unit Testing and SIT to be done.

**Comment by mbharathm** [comment]
Dev is completed, Test document to be prepared and sent to David for Sign-off.
